# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
#
# This file was autogenerated by Weaver. Do not edit it by hand.

module OpenTelemetry
  module SDK
    module Metrics
      module OtelMetrics
        # @!group SDK Metrics

        # The number of log records for which the export has finished, either successful or failed.
        #
        # For successful exports, `error.type` MUST NOT be set. For failed exports, `error.type` MUST contain the failure cause.
        # For exporters with partial success semantics (e.g. OTLP with `rejected_log_records`), rejected log records MUST count as failed and only non-rejected log records count as success.
        # If no rejection reason is available, `rejected` SHOULD be used as value for `error.type`.
        #
        # Instrument: counter
        # Unit: {log_record}
        # @note Stability Level: development
        OTEL_SDK_EXPORTER_LOG_EXPORTED = 'otel.sdk.exporter.log.exported'

        def self.create_otel_sdk_exporter_log_exported(meter)
          meter.create_counter(
            name: OTEL_SDK_EXPORTER_LOG_EXPORTED,
            description: 'The number of log records for which the export has finished, either successful or failed.',
            unit: '{log_record}'
          )
        end

        # The number of log records which were passed to the exporter, but that have not been exported yet (neither successful, nor failed).
        #
        # For successful exports, `error.type` MUST NOT be set. For failed exports, `error.type` MUST contain the failure cause.
        #
        # Instrument: updowncounter
        # Unit: {log_record}
        # @note Stability Level: development
        OTEL_SDK_EXPORTER_LOG_INFLIGHT = 'otel.sdk.exporter.log.inflight'

        def self.create_otel_sdk_exporter_log_inflight(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_EXPORTER_LOG_INFLIGHT,
            description: 'The number of log records which were passed to the exporter, but that have not been exported yet (neither successful, nor failed).',
            unit: '{log_record}'
          )
        end

        # The number of metric data points for which the export has finished, either successful or failed.
        #
        # For successful exports, `error.type` MUST NOT be set. For failed exports, `error.type` MUST contain the failure cause.
        # For exporters with partial success semantics (e.g. OTLP with `rejected_data_points`), rejected data points MUST count as failed and only non-rejected data points count as success.
        # If no rejection reason is available, `rejected` SHOULD be used as value for `error.type`.
        #
        # Instrument: counter
        # Unit: {data_point}
        # @note Stability Level: development
        OTEL_SDK_EXPORTER_METRIC_DATA_POINT_EXPORTED = 'otel.sdk.exporter.metric_data_point.exported'

        def self.create_otel_sdk_exporter_metric_data_point_exported(meter)
          meter.create_counter(
            name: OTEL_SDK_EXPORTER_METRIC_DATA_POINT_EXPORTED,
            description: 'The number of metric data points for which the export has finished, either successful or failed.',
            unit: '{data_point}'
          )
        end

        # The number of metric data points which were passed to the exporter, but that have not been exported yet (neither successful, nor failed).
        #
        # For successful exports, `error.type` MUST NOT be set. For failed exports, `error.type` MUST contain the failure cause.
        #
        # Instrument: updowncounter
        # Unit: {data_point}
        # @note Stability Level: development
        OTEL_SDK_EXPORTER_METRIC_DATA_POINT_INFLIGHT = 'otel.sdk.exporter.metric_data_point.inflight'

        def self.create_otel_sdk_exporter_metric_data_point_inflight(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_EXPORTER_METRIC_DATA_POINT_INFLIGHT,
            description: 'The number of metric data points which were passed to the exporter, but that have not been exported yet (neither successful, nor failed).',
            unit: '{data_point}'
          )
        end

        # The duration of exporting a batch of telemetry records.
        #
        # This metric defines successful operations using the full success definitions for [http](https://github.com/open-telemetry/opentelemetry-proto/blob/v1.5.0/docs/specification.md#full-success-1) and [grpc](https://github.com/open-telemetry/opentelemetry-proto/blob/v1.5.0/docs/specification.md#full-success). Anything else is defined as an unsuccessful operation. For successful operations, `error.type` MUST NOT be set. For unsuccessful export operations, `error.type` MUST contain a relevant failure cause.
        #
        # Instrument: histogram
        # Unit: s
        # @note Stability Level: development
        OTEL_SDK_EXPORTER_OPERATION_DURATION = 'otel.sdk.exporter.operation.duration'

        def self.create_otel_sdk_exporter_operation_duration(meter)
          meter.create_histogram(
            name: OTEL_SDK_EXPORTER_OPERATION_DURATION,
            description: 'The duration of exporting a batch of telemetry records.',
            unit: 's'
          )
        end

        # The number of spans for which the export has finished, either successful or failed.
        #
        # For successful exports, `error.type` MUST NOT be set. For failed exports, `error.type` MUST contain the failure cause.
        # For exporters with partial success semantics (e.g. OTLP with `rejected_spans`), rejected spans MUST count as failed and only non-rejected spans count as success.
        # If no rejection reason is available, `rejected` SHOULD be used as value for `error.type`.
        #
        # Instrument: counter
        # Unit: {span}
        # @note Stability Level: development
        OTEL_SDK_EXPORTER_SPAN_EXPORTED = 'otel.sdk.exporter.span.exported'

        def self.create_otel_sdk_exporter_span_exported(meter)
          meter.create_counter(
            name: OTEL_SDK_EXPORTER_SPAN_EXPORTED,
            description: 'The number of spans for which the export has finished, either successful or failed.',
            unit: '{span}'
          )
        end

        # Deprecated, use `otel.sdk.exporter.span.exported` instead.
        #
        # Instrument: updowncounter
        # Unit: {span}
        # @note Stability Level: development
        # @deprecated Replaced by `otel.sdk.exporter.span.exported`.
        OTEL_SDK_EXPORTER_SPAN_EXPORTED_COUNT = 'otel.sdk.exporter.span.exported.count'

        def self.create_otel_sdk_exporter_span_exported_count(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_EXPORTER_SPAN_EXPORTED_COUNT,
            description: 'Deprecated, use `otel.sdk.exporter.span.exported` instead.',
            unit: '{span}'
          )
        end

        # The number of spans which were passed to the exporter, but that have not been exported yet (neither successful, nor failed).
        #
        # For successful exports, `error.type` MUST NOT be set. For failed exports, `error.type` MUST contain the failure cause.
        #
        # Instrument: updowncounter
        # Unit: {span}
        # @note Stability Level: development
        OTEL_SDK_EXPORTER_SPAN_INFLIGHT = 'otel.sdk.exporter.span.inflight'

        def self.create_otel_sdk_exporter_span_inflight(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_EXPORTER_SPAN_INFLIGHT,
            description: 'The number of spans which were passed to the exporter, but that have not been exported yet (neither successful, nor failed).',
            unit: '{span}'
          )
        end

        # Deprecated, use `otel.sdk.exporter.span.inflight` instead.
        #
        # Instrument: updowncounter
        # Unit: {span}
        # @note Stability Level: development
        # @deprecated Replaced by `otel.sdk.exporter.span.inflight`.
        OTEL_SDK_EXPORTER_SPAN_INFLIGHT_COUNT = 'otel.sdk.exporter.span.inflight.count'

        def self.create_otel_sdk_exporter_span_inflight_count(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_EXPORTER_SPAN_INFLIGHT_COUNT,
            description: 'Deprecated, use `otel.sdk.exporter.span.inflight` instead.',
            unit: '{span}'
          )
        end

        # The number of logs submitted to enabled SDK Loggers.
        #
        # Instrument: counter
        # Unit: {log_record}
        # @note Stability Level: development
        OTEL_SDK_LOG_CREATED = 'otel.sdk.log.created'

        def self.create_otel_sdk_log_created(meter)
          meter.create_counter(
            name: OTEL_SDK_LOG_CREATED,
            description: 'The number of logs submitted to enabled SDK Loggers.',
            unit: '{log_record}'
          )
        end

        # The duration of the collect operation of the metric reader.
        #
        # For successful collections, `error.type` MUST NOT be set. For failed collections, `error.type` SHOULD contain the failure cause.
        # It can happen that metrics collection is successful for some MetricProducers, while others fail. In that case `error.type` SHOULD be set to any of the failure causes.
        #
        # Instrument: histogram
        # Unit: s
        # @note Stability Level: development
        OTEL_SDK_METRIC_READER_COLLECTION_DURATION = 'otel.sdk.metric_reader.collection.duration'

        def self.create_otel_sdk_metric_reader_collection_duration(meter)
          meter.create_histogram(
            name: OTEL_SDK_METRIC_READER_COLLECTION_DURATION,
            description: 'The duration of the collect operation of the metric reader.',
            unit: 's'
          )
        end

        # The number of log records for which the processing has finished, either successful or failed.
        #
        # For successful processing, `error.type` MUST NOT be set. For failed processing, `error.type` MUST contain the failure cause.
        # For the SDK Simple and Batching Log Record Processor a log record is considered to be processed already when it has been submitted to the exporter, not when the corresponding export call has finished.
        #
        # Instrument: counter
        # Unit: {log_record}
        # @note Stability Level: development
        OTEL_SDK_PROCESSOR_LOG_PROCESSED = 'otel.sdk.processor.log.processed'

        def self.create_otel_sdk_processor_log_processed(meter)
          meter.create_counter(
            name: OTEL_SDK_PROCESSOR_LOG_PROCESSED,
            description: 'The number of log records for which the processing has finished, either successful or failed.',
            unit: '{log_record}'
          )
        end

        # The maximum number of log records the queue of a given instance of an SDK Log Record processor can hold.
        #
        # Only applies to Log Record processors which use a queue, e.g. the SDK Batching Log Record Processor.
        #
        # Instrument: updowncounter
        # Unit: {log_record}
        # @note Stability Level: development
        OTEL_SDK_PROCESSOR_LOG_QUEUE_CAPACITY = 'otel.sdk.processor.log.queue.capacity'

        def self.create_otel_sdk_processor_log_queue_capacity(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_PROCESSOR_LOG_QUEUE_CAPACITY,
            description: 'The maximum number of log records the queue of a given instance of an SDK Log Record processor can hold.',
            unit: '{log_record}'
          )
        end

        # The number of log records in the queue of a given instance of an SDK log processor.
        #
        # Only applies to log record processors which use a queue, e.g. the SDK Batching Log Record Processor.
        #
        # Instrument: updowncounter
        # Unit: {log_record}
        # @note Stability Level: development
        OTEL_SDK_PROCESSOR_LOG_QUEUE_SIZE = 'otel.sdk.processor.log.queue.size'

        def self.create_otel_sdk_processor_log_queue_size(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_PROCESSOR_LOG_QUEUE_SIZE,
            description: 'The number of log records in the queue of a given instance of an SDK log processor.',
            unit: '{log_record}'
          )
        end

        # The number of spans for which the processing has finished, either successful or failed.
        #
        # For successful processing, `error.type` MUST NOT be set. For failed processing, `error.type` MUST contain the failure cause.
        # For the SDK Batching Span Processor, once the full batch is queued, but not yet sent, the sum of span received by the processor is being reported.
        # For the SDK Batching Span Processor, every successfully exported span (i.e., status code is not "FAILED") is reported as successfully processed.
        # For the SDK Batching Span Processor, every span batch that failed to export, individually errors, every span in the batch is reported as failed.
        #
        # Instrument: counter
        # Unit: {span}
        # @note Stability Level: development
        OTEL_SDK_PROCESSOR_SPAN_PROCESSED = 'otel.sdk.processor.span.processed'

        def self.create_otel_sdk_processor_span_processed(meter)
          meter.create_counter(
            name: OTEL_SDK_PROCESSOR_SPAN_PROCESSED,
            description: 'The number of spans for which the processing has finished, either successful or failed.',
            unit: '{span}'
          )
        end

        # The maximum number of spans the queue of a given instance of an SDK Span processor can hold.
        #
        # Only applies to span processors which use a queue, e.g. the SDK Batching Span Processor.
        #
        # Instrument: updowncounter
        # Unit: {span}
        # @note Stability Level: development
        OTEL_SDK_PROCESSOR_SPAN_QUEUE_CAPACITY = 'otel.sdk.processor.span.queue.capacity'

        def self.create_otel_sdk_processor_span_queue_capacity(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_PROCESSOR_SPAN_QUEUE_CAPACITY,
            description: 'The maximum number of spans the queue of a given instance of an SDK Span processor can hold.',
            unit: '{span}'
          )
        end

        # The number of spans in the queue of a given instance of an SDK Span processor.
        #
        # Only applies to span processors which use a queue, e.g. the SDK Batching Span Processor.
        #
        # Instrument: updowncounter
        # Unit: {span}
        # @note Stability Level: development
        OTEL_SDK_PROCESSOR_SPAN_QUEUE_SIZE = 'otel.sdk.processor.span.queue.size'

        def self.create_otel_sdk_processor_span_queue_size(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_PROCESSOR_SPAN_QUEUE_SIZE,
            description: 'The number of spans in the queue of a given instance of an SDK Span processor.',
            unit: '{span}'
          )
        end

        # The number of spans created by this tracer sdk.
        #
        # The metric SHOULD be of type Counter.
        #
        # Instrument: counter
        # Unit: {span}
        # @note Stability Level: development
        OTEL_SDK_SPAN_STARTED = 'otel.sdk.span.started'

        def self.create_otel_sdk_span_started(meter)
          meter.create_counter(
            name: OTEL_SDK_SPAN_STARTED,
            description: 'The number of spans created by this tracer sdk.',
            unit: '{span}'
          )
        end

        # The number of spans created by this tracer sdk that are in the recording state.
        #
        # Instrument: updowncounter
        # Unit: {span}
        # @note Stability Level: development
        OTEL_SDK_SPAN_LIVE = 'otel.sdk.span.live'

        def self.create_otel_sdk_span_live(meter)
          meter.create_up_down_counter(
            name: OTEL_SDK_SPAN_LIVE,
            description: 'The number of spans created by this tracer sdk that are in the recording state.',
            unit: '{span}'
          )
        end

        # @!endgroup
      end
    end
  end
end
